CREATE TABLE rol(
rolId SERIAL,
tipoRol VARCHAR(10) NOT NULL,
descripcion VARCHAR(100) NOT NULL,
activo BOOLEAN DEFAULT TRUE,
createdAt TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
updatedAt TIMESTAMP WITH TIME ZONE,
CONSTRAINT rolId_PK PRIMARY KEY (rolId)
);

CREATE TABLE tipo_cliente(
tipoClienteId SERIAL,
descripcion VARCHAR(20),
activo BOOLEAN DEFAULT TRUE,
createdAt TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
updatedAt TIMESTAMP WITH TIME ZONE,
CONSTRAINT tipoClienteId_PK PRIMARY KEY (tipoClienteId)
);

CREATE TABLE departamento(
dptoId SERIAL,
nombreDpto VARCHAR(15) NOT NULL,
activo BOOLEAN DEFAULT TRUE,
createdAt TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
updatedAt TIMESTAMP WITH TIME ZONE,
CONSTRAINT departamentoId_PK PRIMARY KEY (dptoId)
);

CREATE TABLE faja(
fajaId SERIAL,
descripcion char(1) NOT NULL,
createdAt TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
updatedAt TIMESTAMP WITH TIME ZONE,
CONSTRAINT faja_PK PRIMARY KEY (fajaId),
CONSTRAINT desc_CHK CHECK (descripcion ~ '^[^0-9]*$')
);

CREATE TABLE dato_empresa(
datoEmpresaId SERIAL,
nombreEmpresa VARCHAR(50) NOT NULL
RUC VARCHAR(15) NOT NULL,
nombreRepresentante1 VARCHAR(30) NOT NULL,
ciRepresentante1 INTEGER NOT NULL,
nombreRepresentante2 VARCHAR(30) DEFAULT NULL,
ciRepresentante2 INTEGER DEFAULT NULL,
antiguedad VARCHAR(10) NOT NULL,
active BOOLEAN DEFAULT TRUE,
createdAt TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
updatedAt TIMESTAMP WITH TIME ZONE,
CONSTRAINT datoEmpresaId_PK PRIMARY KEY(datoEmpresaId)
);

CREATE TABLE ciudad(
ciudadId SERIAL,
dptoId INTEGER NOT NULL,
description VARCHAR(40),
active BOOLEAN DEFAULT TRUE,
createdAt TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
updatedAt TIMESTAMP WITH TIME ZONE,
CONSTRAINT ciudadId_PK PRIMARY KEY (ciudadId),
CONSTRAINT dptoId_FK FOREIGN KEY (dptoId) REFERENCES departamento(dptoId)
);

CREATE TABLE dato_cliente(
datoClienteId SERIAL,
ciudadId INTEGER NOT NULL,
fajaId INTEGER NOT NULL,
tipoClienteId INTEGER NOT NULL,
direccionParticular VARCHAR(100) NOT NULL,
documento INTEGER NOT NULL,
edad INTEGER NOT NULL,
contact VARCHAR(30) NOT NULL,
lat VARCHAR(50) DEFAULT NULL,
lng VARCHAR(50) DEFAULT NULL,
createdAt TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
updatedAt TIMESTAMP WITH TIME ZONE,
CONSTRAINT datoClienteId_PK PRIMARY KEY (datoClienteId),
CONSTRAINT ciudadId_FK FOREIGN KEY (ciudadId) REFERENCES ciudad(ciudadId),
CONSTRAINT fajaId_FK FOREIGN KEY (fajaId) REFERENCES faja(fajaId),
CONSTRAINT tipoCliente_FK FOREIGN KEY (tipoClienteId) REFERENCES tipo_cliente(tipoClienteId)
);

CREATE TABLE usuario(
usuarioId SERIAL,
rolId INTEGER NOT NULL,
datoClienteId INTEGER DEFAULT NULL,
username VARCHAR(10) NOT NULL,
pasword VARCHAR(90) NOT NULL,
usermail VARCHAR(45) NOT NULL,
avatar VARCHAR(200) DEFAULT NULL,
active BOOLEAN DEFAULT TRUE,
createdAt TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
updatedAt TIMESTAMP WITH TIME ZONE,
CONSTRAINT usuarioId_PK PRIMARY KEY (usuarioId),
CONSTRAINT rolId_FK FOREIGN KEY (rolId) REFERENCES rol(rolId),
CONSTRAINT datoClienteId_FK FOREIGN KEY (datoClienteId) REFERENCES dato_cliente(datoClienteId),
CONSTRAINT username_UC UNIQUE (username),
CONSTRAINT usermail_UC UNIQUE (usermail)
);
